<?php
// --- konawiki3 directories setting ---
// generated by konawiki3-auto-install
define('KONA3_DIR_ENGINE',  '/Users/kujirahand/repos/konawiki3/kona3engine');
define('KONA3_DIR_SKIN',    '/Users/kujirahand/repos/konawiki3/skin');
define('KONA3_DIR_DATA',    '/Users/kujirahand/repos/konawiki3/data');
define('KONA3_DIR_PRIVATE', '/Users/kujirahand/repos/konawiki3/private');
define('KONA3_DIR_CACHE',   '/Users/kujirahand/repos/konawiki3/cache');